# k nearest neighbors

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [2]:
df = pd.read_csv("Social_Network_Ads.csv")

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df.shape


(400, 5)

In [5]:
# This X in datafream

X = df.iloc[:,2:4] 

In [6]:
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [7]:
# we convert X in nympy array using ".values"

X = df.iloc[:, 2:4].values

In [8]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [9]:
X.shape

(400, 2)

In [10]:
# This Y in datafream

Y = df.iloc[:, -1]

In [11]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [12]:
Y.shape

(400,)

In [13]:
# we convert X in nympy array using ".values"

Y = df.iloc[:, -1].values

In [14]:
Y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [16]:
X_train.shape

(320, 2)

In [17]:
X_test.shape

(80, 2)

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [19]:
X_train = scaler.fit_transform(X_train)
X_train

array([[-0.22164985,  0.57697706],
       [ 1.02775851, -0.99150426],
       [-1.08662486,  1.33320912],
       [ 0.35500016,  0.04481375],
       [ 0.93165017, -0.65540112],
       [ 0.4511085 , -0.45934096],
       [-0.89440819,  0.46494268],
       [-0.02943318,  1.86537242],
       [-0.22164985, -0.73942691],
       [ 0.93165017,  0.96909738],
       [-0.70219152,  1.80935523],
       [ 0.93165017, -0.59938393],
       [ 1.89273352, -1.04752145],
       [ 0.83554184,  0.10083094],
       [ 1.12386684,  0.43693408],
       [-0.12554151,  2.06143259],
       [ 1.12386684,  1.9774068 ],
       [ 2.18105852,  0.8850716 ],
       [-0.79829986, -0.7674355 ],
       [ 0.16278349,  0.99710598],
       [-0.50997485,  0.43693408],
       [-1.7593832 ,  0.40892549],
       [-1.85549154,  0.3248997 ],
       [-0.41386652, -0.03921203],
       [-0.02943318, -0.37531517],
       [ 1.98884185,  2.06143259],
       [ 1.98884185,  0.857063  ],
       [-1.4710582 , -0.43133236],
       [ 0.35500016,

In [20]:
X_test = scaler.transform(X_test)
X_test

array([[-1.27884153, -1.21557302],
       [-0.22164985,  0.74502862],
       [-0.02943318,  0.12883954],
       [ 2.18105852, -0.68340972],
       [ 1.21997517, -0.96349567],
       [-0.41386652, -0.29128939],
       [-0.02943318,  0.21286532],
       [ 1.41219184,  2.22948416],
       [ 0.4511085 ,  0.24087392],
       [-0.22164985,  0.49295127],
       [-0.89440819,  0.40892549],
       [ 0.06667516, -0.31929798],
       [-0.70219152, -0.59938393],
       [ 0.16278349, -0.26328079],
       [ 0.83554184, -1.3276074 ],
       [ 0.93165017, -1.27159021],
       [ 0.25889183,  0.12883954],
       [-0.22164985, -0.48734955],
       [-0.02943318, -1.04752145],
       [-1.27884153,  0.38091689],
       [ 1.02775851, -1.04752145],
       [ 1.12386684,  0.52095987],
       [ 0.4511085 ,  0.12883954],
       [-0.99051653, -1.41163318],
       [ 0.25889183,  0.12883954],
       [-0.22164985,  0.04481375],
       [-0.02943318,  0.26888251],
       [ 1.60440851,  1.05312317],
       [-0.22164985,

In [21]:
# 1st method

np.sqrt(X_train.shape[0])

17.88854381999832

In [22]:
k = 17

In [23]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [24]:
# Train our model

knn.fit(X_train, Y_train)

KNeighborsClassifier()

In [25]:
Y_pred = knn.predict(X_test)

In [26]:
Y_pred

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64)

In [27]:
Y_pred.shape

(80,)

In [28]:
Y_test.shape

(80,)

In [29]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_pred)

0.9

In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, Y_pred)

array([[49,  2],
       [ 6, 23]], dtype=int64)