# Precision, Recall, F1_Score

In [1]:
print("Jayswal Umang")

Jayswal Umang


In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("heart.csv")

In [4]:
df.shape

(303, 14)

In [5]:
df.head(6)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   
5   57    1   0       140   192    0        1      148      0      0.4      1   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1  
5   0     1       1

In [6]:
df.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0

In [7]:
X = df.iloc[:, 0:-1]
Y = df.iloc[:, -1]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [10]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [11]:
clf1.fit(X_train, Y_train)

C:\Python 3.10\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [12]:
clf2.fit(X_train, Y_train)

DecisionTreeClassifier()

In [13]:
Y_pred1 = clf1.predict(X_test)
Y_pred2 = clf2.predict(X_test)

In [14]:
from sklearn.metrics import recall_score, precision_score, f1_score, confusion_matrix

In [15]:
print("For Logistic regression Model")
pd.DataFrame(confusion_matrix(Y_test,Y_pred1),columns=list(range(0,2)))

For Logistic regression Model


0   1
0  26   6
1   0  29

In [16]:
print("Precision - ",precision_score(Y_test,Y_pred1))
print("Recall - ",recall_score(Y_test,Y_pred1))
print("F1 score - ",f1_score(Y_test,Y_pred1))

Precision -  0.8285714285714286
Recall -  1.0
F1 score -  0.90625


In [17]:
print("For Decision Tree Model")
pd.DataFrame(confusion_matrix(Y_test,Y_pred2),columns=list(range(0,2)))

For Decision Tree Model


0   1
0  24   8
1   2  27

In [18]:
print("Precision - ",precision_score(Y_test,Y_pred2))
print("Recall - ",recall_score(Y_test,Y_pred2))
print("F1 score - ",f1_score(Y_test,Y_pred2))

Precision -  0.7714285714285715
Recall -  0.9310344827586207
F1 score -  0.8437500000000001


# Multi_Class Precisio, Recall, F1_Score

In [19]:
precision_score(Y_test, Y_pred1, average=None)

array([1.        , 0.82857143])

In [20]:
precision_score(Y_test, Y_pred1, average="macro")

0.9142857142857144

In [21]:
precision_score(Y_test, Y_pred1, average="weighted")

0.9185011709601872

In [22]:
recall_score(Y_test,Y_pred2, average=None)


array([0.75      , 0.93103448])

In [23]:
recall_score(Y_test,Y_pred2, average="macro")

0.8405172413793103

In [24]:
recall_score(Y_test,Y_pred2, average="weighted")

0.8360655737704918

In [25]:
f1_score(Y_test,Y_pred1, average=None)

array([0.89655172, 0.90625   ])

In [26]:
f1_score(Y_test,Y_pred1, average="macro")

0.9014008620689655

In [27]:
f1_score(Y_test,Y_pred1, average="weighted")

0.901162379875636

In [28]:
from sklearn.metrics import classification_report

In [29]:
print(classification_report(Y_test, Y_pred2))

              precision    recall  f1-score   support

           0       0.92      0.75      0.83        32
           1       0.77      0.93      0.84        29

    accuracy                           0.84        61
   macro avg       0.85      0.84      0.84        61
weighted avg       0.85      0.84      0.84        61

