# NumPy Intro :-

In [1]:
import numpy as np

In [2]:
print("Umang Jayswal")

Umang Jayswal


In [3]:
myarr = np.array([35, 54, 33, 7]) 

In [4]:
myarr

array([35, 54, 33,  7])

In [5]:
myarr1 = np.array([[5, 55, 56,5]] , np.int64)

In [6]:
myarr1

array([[ 5, 55, 56,  5]], dtype=int64)

In [7]:
print(myarr) # Using print statement

[35 54 33  7]


In [8]:
myarr[2] 

33

In [9]:
myarr1[0]

array([ 5, 55, 56,  5], dtype=int64)

In [10]:
myarr.dtype

dtype('int32')

In [11]:
myarr1.dtype

dtype('int64')

In [12]:
myarr.shape

(4,)

In [13]:
myarr1.shape

(1, 4)

In [14]:
myarr1[0, 2] = 65  #change elements in array

In [15]:
myarr1

array([[ 5, 55, 65,  5]], dtype=int64)

# Arry creation : Conversion from other Python structures

In [16]:
listarray = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [17]:
listarray


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
listarray.dtype

dtype('int32')

In [19]:
listarray.shape

(3, 4)

In [20]:
listarray.size

12

In [21]:
zero = np.zeros((3,4))

In [22]:
zero.shape

(3, 4)

In [23]:
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
zero.dtype

dtype('float64')

In [25]:
rng = np.arange(10)

In [26]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
lspace = np.linspace(1,50,10)

In [28]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [29]:
lspace1 = np.linspace(1,10,10)

In [30]:
lspace1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
lspace2 = np.linspace(1,5,4)

In [32]:
lspace2

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [33]:
emp = np.empty((2,3)) #create empty array

In [34]:
emp

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
id = np.identity(5)

In [36]:
id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
id.shape

(5, 5)

In [38]:
id.shape

(5, 5)

In [39]:
 np.identity(5)  #another way to print

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
arr = np.arange(100) 

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [42]:
arr.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [43]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
arr1 = np.arange(6)  #second example

In [45]:
arr1

array([0, 1, 2, 3, 4, 5])

In [46]:
arr1.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [47]:
arr1.ravel()

array([0, 1, 2, 3, 4, 5])

# NumPy Axis

In [48]:
x = np.array([[1,2,3], [4,5,6], [7,1,0]])

In [49]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [50]:
x.sum(axis=0)  # 1+4+7=12, 2+5+1=8, 3+6+0=9

array([12,  8,  9])

In [51]:
x.sum(axis=1)  # 1+2+3=6, 4+5+6=15, 7+1+0=8

array([ 6, 15,  8])

In [52]:
x.T  #Transpose array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [53]:
for i in x:
    print(i)

[1 2 3]
[4 5 6]
[7 1 0]


In [54]:
x.flat

In [55]:
for item in x.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [56]:
x.ndim

2

In [57]:
x.size

9

In [58]:
x.nbytes #how many bytes used in array

36

In [59]:
#Some methods in NumPy

In [60]:
one = np.array([1,2,55,78, 5, 10])  #Create 1D array 

In [61]:
one.argmax()  #index[3] = 78

3

In [62]:
one.argmin()

0

In [63]:
one.argsort()

array([0, 1, 4, 5, 2, 3], dtype=int64)

In [64]:
x  #Using 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
x.argmin()

8

In [66]:
x.argmin(axis=0)

array([0, 2, 2], dtype=int64)

In [67]:
x.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [68]:
x.argmax()

6

In [69]:
x.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [70]:
x.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [71]:
x.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [72]:
x.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [73]:
x.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [74]:
x.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [75]:
#Some mathematical operations in array

In [76]:
A = np.array([[0,1,2], [3,2,4], [6,0,4]])

In [77]:
B = np.array([[0,2,1], [0,5,7], [0,0,1]])

In [78]:
A

array([[0, 1, 2],
       [3, 2, 4],
       [6, 0, 4]])

In [79]:
B

array([[0, 2, 1],
       [0, 5, 7],
       [0, 0, 1]])

In [80]:
A + B  #we can't do this mathamatical operations in list  

array([[ 0,  3,  3],
       [ 3,  7, 11],
       [ 6,  0,  5]])

In [81]:
A * B

array([[ 0,  2,  2],
       [ 0, 10, 28],
       [ 0,  0,  4]])

In [82]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 1.41421356, 2.        ],
       [2.44948974, 0.        , 2.        ]])

In [83]:
A.sum()

22

In [84]:
A.max()

6

In [85]:
A.min()

0

In [86]:
A

array([[0, 1, 2],
       [3, 2, 4],
       [6, 0, 4]])

In [87]:
np.where(A>2)

(array([1, 1, 2, 2], dtype=int64), array([0, 2, 0, 2], dtype=int64))

In [88]:
type(np.where(A>2))

tuple

In [89]:
np.count_nonzero(A)

7

In [90]:
np.nonzero(A)

(array([0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 2], dtype=int64))

In [91]:
A[1,2] = 0

In [92]:
np.nonzero(A)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 0, 2], dtype=int64))